server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://view-localhost:9000
  datasource:
    username: moez
    url: jdbc:h2:mem:demodb
    driverClassName: org.h2.Driver
    password: moezmejri
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
  h2:
    console.enabled: true